# Generated by Django 5.2.5 on 2025-08-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='no_picture.jpg', null=True, upload_to='ingredients'),
        ),
    ]
